{
  "type": "record",
  "name": "Wide",
  "namespace": "bench",
  "fields": [
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "ts",
      "type": "long"
    },
    {
      "name": "s0",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s1",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s2",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s3",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s4",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s5",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s6",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s7",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s8",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s9",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s10",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s11",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s12",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s13",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s14",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "s15",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "n0",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n1",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n2",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n3",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n4",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n5",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n6",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n7",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n8",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n9",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n10",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "n11",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "d0",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "d1",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "d2",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "d3",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "d4",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "d5",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "d6",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "d7",
      "type": [
        "null",
        "double"
      ],
      "default": null
    },
    {
      "name": "b0",
      "type": "boolean"
    },
    {
      "name": "b1",
      "type": "boolean"
    },
    {
      "name": "b2",
      "type": "boolean"
    },
    {
      "name": "b3",
      "type": "boolean"
    },
    {
      "name": "b4",
      "type": "boolean"
    },
    {
      "name": "b5",
      "type": "boolean"
    }
  ]
}
